#!/usr/bin/env python3
"""Generate the panel-mapping seed SQL for the C-level Sellable Potential dashboard.

Reads a discovery_crm_products CSV export and writes an idempotent migration
that:

  1. Inserts a gui_crm_service_pages row for every panel_key reachable via
     ``shared.sellable.panel_mapping.classify`` (so the legacy mapping seed
     table has a valid foreign key).
  2. Links each gui_crm_service_pages row to the gui_panel_definition row
     with the same key (panel_key column added by 005_panel_sellable_schema).
  3. Re-classifies gui_crm_service_mapping_seed for every productid in the
     CSV (UPSERT). Operator-managed gui_crm_service_mapping_override rows
     are NOT touched.

Usage:
  python Datalake-Platform-GUI/shared/sellable/generate_panel_mapping_sql.py \
    --csv "C:/Users/PC/Desktop/discovery_crm_products-202605040029.csv" \
    --out Datalake-Platform-GUI/services/customer-api/migrations/webui/010_seed_full_product_mapping.sql

Run from the repo root or any directory.
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_GUI_ROOT = _HERE.parents[1]


def _ensure_path() -> None:
    if str(_GUI_ROOT) not in sys.path:
        sys.path.insert(0, str(_GUI_ROOT))


def _sql_str(s: str) -> str:
    return (s or "").replace("'", "''")


def _load_yaml_pages(yaml_path: Path) -> dict[str, dict[str, str]]:
    """Return {page_key: {label, resource_unit, gui_tab_binding}} from the YAML registry."""
    try:
        import yaml  # type: ignore
    except ImportError as exc:  # pragma: no cover - dev env always has PyYAML
        raise SystemExit("PyYAML is required for label lookup; pip install pyyaml") from exc
    with open(yaml_path, encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    pages = data.get("pages") or {}
    out: dict[str, dict[str, str]] = {}
    for k, v in pages.items():
        if not isinstance(v, dict):
            continue
        out[str(k)] = {
            "label": str(v.get("label") or k),
            "resource_unit": str(v.get("resource_unit") or "Adet"),
            "gui_tab_binding": str(v.get("gui_tab_binding") or "other"),
        }
    return out


def _emit(csv_path: Path, out_path: Path, yaml_path: Path | None) -> int:
    _ensure_path()
    from shared.sellable.panel_mapping import classify_batch, known_panel_keys

    with open(csv_path, encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    classifications = classify_batch(rows)
    counts: dict[str, int] = {}
    for _, pk in classifications:
        counts[pk] = counts.get(pk, 0) + 1

    panels = sorted(known_panel_keys())
    yaml_pages = _load_yaml_pages(yaml_path) if yaml_path else {}

    lines: list[str] = []
    lines.append("-- 010_seed_full_product_mapping.sql")
    lines.append("-- Generated by shared/sellable/generate_panel_mapping_sql.py")
    lines.append(f"-- Source CSV: {csv_path.name}")
    lines.append(f"-- Total products classified: {len(classifications)}")
    lines.append("-- Per-panel counts: " + ", ".join(f"{k}={v}" for k, v in sorted(counts.items())))
    lines.append("--")
    lines.append("-- Idempotent UPSERT: gui_crm_service_pages get linked to gui_panel_definition,")
    lines.append("-- and gui_crm_service_mapping_seed is rewritten for every productid in the CSV.")
    lines.append("-- Operator overrides in gui_crm_service_mapping_override are untouched.")
    lines.append("BEGIN;")
    lines.append("")

    lines.append("-- 1) Ensure every reachable panel_key has a matching gui_crm_service_pages row")
    lines.append("--    and that gui_crm_service_pages.panel_key links it to gui_panel_definition.")
    for pk in panels:
        meta = yaml_pages.get(pk, {})
        category_label = meta.get("label") or pk
        gtb = meta.get("gui_tab_binding") or pk
        page_unit = meta.get("resource_unit") or "Adet"
        lines.append(
            "INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit, panel_key) "
            f"VALUES ('{_sql_str(pk)}', '{_sql_str(category_label)}', '{_sql_str(gtb)}', '{_sql_str(page_unit)}', '{_sql_str(pk)}') "
            "ON CONFLICT (page_key) DO UPDATE SET "
            "category_label = EXCLUDED.category_label, "
            "gui_tab_binding = EXCLUDED.gui_tab_binding, "
            "resource_unit = EXCLUDED.resource_unit, "
            "panel_key = EXCLUDED.panel_key;"
        )

    lines.append("")
    lines.append("-- 2) Re-classify product seed mapping. UNMATCHED ('other') is allowed but the")
    lines.append("--    operator UI will surface those rows for manual decision.")
    for pid, pk in classifications:
        lines.append(
            "INSERT INTO gui_crm_service_mapping_seed (productid, page_key) "
            f"VALUES ('{_sql_str(pid)}', '{_sql_str(pk)}') "
            "ON CONFLICT (productid) DO UPDATE SET page_key = EXCLUDED.page_key;"
        )

    lines.append("")
    lines.append("COMMIT;")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"Wrote {out_path} ({len(lines)} lines, "
        f"products={len(classifications)}, panels={len(panels)})"
    )
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", required=True, help="discovery_crm_products CSV export")
    ap.add_argument("--out", required=True, help="Output .sql migration path")
    ap.add_argument(
        "--yaml",
        default=str(_GUI_ROOT / "config" / "crm_service_mapping.yaml"),
        help="YAML registry to source labels/units from (default: config/crm_service_mapping.yaml)",
    )
    args = ap.parse_args()
    yaml_path = Path(args.yaml) if args.yaml else None
    return _emit(Path(args.csv), Path(args.out), yaml_path)


if __name__ == "__main__":
    raise SystemExit(main())
