#!/usr/bin/env python3
"""
Generate SQL migration for the CRM service mapping registry.

Two modes:
  --mode rebuild  (default)  : Drops and recreates gui_crm_service_pages + seed tables.
                                Used by the initial datalake migration scaffold.
  --mode patch               : Idempotent UPSERT/UPDATE patch — adds new page_key rows
                                (categories) and re-classifies seed productids based on
                                the current rule pack. Safe to apply over an existing
                                webui-db schema.

Run from repository root (datalake-platform) with:
  PYTHONPATH=Datalake-Platform-GUI python Datalake-Platform-GUI/shared/service_mapping/generate_seed_sql.py \
    --csv datalake/collectors/CRM/Dynamics365/analyze_scripts/discovery_crm_products_202604242055.csv \
    --out datalake/SQL/CRM/migrations/2026-04-24-gui-crm-service-mapping.sql

Patch example:
  PYTHONPATH=Datalake-Platform-GUI python Datalake-Platform-GUI/shared/service_mapping/generate_seed_sql.py \
    --mode patch \
    --csv "C:/Users/PC/Desktop/datalake-crm-products.csv" \
    --out Datalake-Platform-GUI/services/customer-api/migrations/webui/004_granular_pages.sql
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_GUI_ROOT = _HERE.parents[1]


def _ensure_path() -> None:
    if str(_GUI_ROOT) not in sys.path:
        sys.path.insert(0, str(_GUI_ROOT))


def _sql_str(s: str) -> str:
    return (s or "").replace("'", "''")


def _classify_csv_rows(csv_path: Path, categories: dict, rules: list) -> list[tuple[str, str]]:
    """Return list of (productid, page_key) using the current rule pack."""
    from shared.service_mapping.rules import match_product_name  # local import after path fix

    valid_pages = set(categories.keys())
    out: list[tuple[str, str]] = []
    with open(csv_path, encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            pid = (row.get("productid") or "").strip().strip('"')
            name = (row.get("name") or "").strip()
            if not pid:
                continue
            page_key, _meta = match_product_name(name, categories=categories, rules=rules)
            if page_key not in valid_pages:
                page_key = "other"
            out.append((pid, page_key))
    return out


def _emit_rebuild(csv_path: Path, out_path: Path, categories: dict, rules: list) -> int:
    lines: list[str] = []
    lines.append("-- Generated by shared/service_mapping/generate_seed_sql.py (mode=rebuild)")
    lines.append("-- CRM GUI service mapping: pages registry + per-product seed + view + legacy drop")
    lines.append("BEGIN;")
    lines.append("")
    lines.append("DROP VIEW IF EXISTS v_gui_crm_product_mapping CASCADE;")
    lines.append("DROP TABLE IF EXISTS gui_crm_service_mapping_seed CASCADE;")
    lines.append("DROP TABLE IF EXISTS gui_crm_service_mapping_override CASCADE;")
    lines.append("DROP TABLE IF EXISTS gui_crm_service_pages CASCADE;")
    lines.append("")
    lines.append("CREATE TABLE gui_crm_service_pages (")
    lines.append("    page_key          TEXT PRIMARY KEY,")
    lines.append("    category_label    TEXT NOT NULL,")
    lines.append("    gui_tab_binding   TEXT NOT NULL,")
    lines.append("    resource_unit     TEXT NOT NULL DEFAULT 'Adet',")
    lines.append("    icon              TEXT,")
    lines.append("    route_hint        TEXT,")
    lines.append("    tab_hint          TEXT,")
    lines.append("    sub_tab_hint      TEXT")
    lines.append(");")
    lines.append("")

    for pk, meta in sorted(categories.items(), key=lambda x: x[0]):
        lab = _sql_str(str(meta.get("label") or pk))
        gtb = _sql_str(str(meta.get("gui_tab_binding") or "other"))
        ru = _sql_str(str(meta.get("resource_unit") or "Adet"))
        lines.append(
            "INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) "
            f"VALUES ('{_sql_str(pk)}', '{lab}', '{gtb}', '{ru}');"
        )

    lines.append("")
    lines.append("CREATE TABLE gui_crm_service_mapping_seed (")
    lines.append("    productid   TEXT PRIMARY KEY,")
    lines.append("    page_key    TEXT NOT NULL REFERENCES gui_crm_service_pages(page_key)")
    lines.append(");")
    lines.append("")

    for pid, page_key in _classify_csv_rows(csv_path, categories, rules):
        lines.append(
            "INSERT INTO gui_crm_service_mapping_seed (productid, page_key) "
            f"VALUES ('{_sql_str(pid)}', '{_sql_str(page_key)}');"
        )

    lines.append("")
    lines.append("CREATE TABLE gui_crm_service_mapping_override (")
    lines.append("    productid    TEXT PRIMARY KEY,")
    lines.append("    page_key     TEXT NOT NULL REFERENCES gui_crm_service_pages(page_key),")
    lines.append("    notes        TEXT,")
    lines.append("    updated_by   TEXT,")
    lines.append("    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()")
    lines.append(");")
    lines.append("")
    lines.append(
        "DO $migrate_manual$\n"
        "BEGIN\n"
        "  IF to_regclass('public.discovery_crm_product_category_alias') IS NOT NULL THEN\n"
        "    INSERT INTO gui_crm_service_mapping_override (productid, page_key, notes, updated_by, updated_at)\n"
        "    SELECT pca.productid,\n"
        "           CASE WHEN pca.category_code IN (SELECT page_key FROM gui_crm_service_pages)\n"
        "                THEN pca.category_code ELSE 'other' END,\n"
        "           COALESCE(pca.notes, 'migrated from discovery_crm_product_category_alias'),\n"
        "           'migration',\n"
        "           now()\n"
        "    FROM   discovery_crm_product_category_alias pca\n"
        "    WHERE  pca.source = 'manual';\n"
        "  END IF;\n"
        "END $migrate_manual$;"
    )
    lines.append("")
    lines.append("CREATE OR REPLACE VIEW v_gui_crm_product_mapping AS")
    lines.append("SELECT")
    lines.append("    pr.productid,")
    lines.append("    pr.name AS product_name,")
    lines.append("    pr.productnumber AS product_number,")
    lines.append("    COALESCE(o.page_key, s.page_key, 'other') AS category_code,")
    lines.append("    pg.category_label,")
    lines.append("    pg.gui_tab_binding,")
    lines.append("    NULL::text AS resource_unit,")
    lines.append(
        "    CASE WHEN o.productid IS NOT NULL THEN 'override' "
        "WHEN s.productid IS NOT NULL THEN 'yaml' ELSE 'default' END AS mapping_source,"
    )
    lines.append(
        "    COALESCE(NULLIF(TRIM(pg.resource_unit), ''), 'Adet') AS page_resource_unit"
    )
    lines.append("FROM   discovery_crm_products pr")
    lines.append("LEFT JOIN gui_crm_service_mapping_seed s ON s.productid = pr.productid")
    lines.append("LEFT JOIN gui_crm_service_mapping_override o ON o.productid = pr.productid")
    lines.append("JOIN   gui_crm_service_pages pg ON pg.page_key = COALESCE(o.page_key, s.page_key, 'other');")
    lines.append("")
    lines.append("DROP TABLE IF EXISTS discovery_crm_product_category_alias CASCADE;")
    lines.append("")
    lines.append("COMMIT;")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(lines)} lines, mode=rebuild)")
    return 0


def _emit_patch(csv_path: Path, out_path: Path, categories: dict, rules: list) -> int:
    """
    Idempotent migration that:
      * INSERTs any new page_key rows (no-op if already present).
      * UPDATEs gui_crm_service_pages metadata for known page_keys (label, binding, unit).
      * UPSERTs gui_crm_service_mapping_seed for every CSV product, but ONLY overwrites the
        existing seed page_key (operator overrides in gui_crm_service_mapping_override are
        untouched).
    Productids that have neither a YAML rule match nor an explicit override remain
    unmatched (no row in gui_crm_service_mapping_seed) so the API can surface them with
    source='unmatched'.
    """
    rows = _classify_csv_rows(csv_path, categories, rules)

    lines: list[str] = []
    lines.append("-- Generated by shared/service_mapping/generate_seed_sql.py (mode=patch)")
    lines.append("-- Idempotent patch: adds granular page_keys and re-classifies seed mappings.")
    lines.append("-- Safe to re-run; gui_crm_service_mapping_override rows are untouched.")
    lines.append("BEGIN;")
    lines.append("")
    lines.append("-- 1) Upsert page registry rows (new granular categories + label refresh).")

    for pk, meta in sorted(categories.items(), key=lambda x: x[0]):
        lab = _sql_str(str(meta.get("label") or pk))
        gtb = _sql_str(str(meta.get("gui_tab_binding") or "other"))
        ru = _sql_str(str(meta.get("resource_unit") or "Adet"))
        lines.append(
            "INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) "
            f"VALUES ('{_sql_str(pk)}', '{lab}', '{gtb}', '{ru}') "
            "ON CONFLICT (page_key) DO UPDATE SET "
            "category_label = EXCLUDED.category_label, "
            "gui_tab_binding = EXCLUDED.gui_tab_binding, "
            "resource_unit = EXCLUDED.resource_unit;"
        )

    lines.append("")
    lines.append("-- 2) Re-classify seed mapping rows. Operator overrides remain untouched.")
    for pid, page_key in rows:
        if page_key == "other":
            # Drop stale seed row so the product surfaces as unmatched (no fake 'other' fallback).
            lines.append(
                f"DELETE FROM gui_crm_service_mapping_seed WHERE productid = '{_sql_str(pid)}';"
            )
        else:
            lines.append(
                "INSERT INTO gui_crm_service_mapping_seed (productid, page_key) "
                f"VALUES ('{_sql_str(pid)}', '{_sql_str(page_key)}') "
                "ON CONFLICT (productid) DO UPDATE SET page_key = EXCLUDED.page_key;"
            )

    lines.append("")
    lines.append("COMMIT;")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(lines)} lines, mode=patch, products={len(rows)})")
    return 0


def main() -> int:
    _ensure_path()
    from shared.service_mapping.rules import load_rule_pack

    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", required=True, help="discovery_crm_products CSV export")
    ap.add_argument("--out", required=True, help="Output .sql path")
    ap.add_argument(
        "--mode",
        choices=("rebuild", "patch"),
        default="rebuild",
        help="rebuild = full DROP/CREATE; patch = idempotent UPSERT/UPDATE",
    )
    args = ap.parse_args()

    csv_path = Path(args.csv)
    out_path = Path(args.out)
    categories, rules = load_rule_pack()

    if args.mode == "patch":
        return _emit_patch(csv_path, out_path, categories, rules)
    return _emit_rebuild(csv_path, out_path, categories, rules)


if __name__ == "__main__":
    raise SystemExit(main())
