#!/usr/bin/env python3
"""
Generate datalake SQL migration: gui_crm_service_pages + gui_crm_service_mapping_seed rows.

Run from repository root (datalake-platform) with:
  PYTHONPATH=Datalake-Platform-GUI python Datalake-Platform-GUI/shared/service_mapping/generate_seed_sql.py \\
    --csv datalake/collectors/CRM/Dynamics365/analyze_scripts/discovery_crm_products_202604242055.csv \\
    --out datalake/SQL/CRM/migrations/2026-04-24-gui-crm-service-mapping.sql
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

# Repo roots
_HERE = Path(__file__).resolve().parent
_GUI_ROOT = _HERE.parents[1]


def _ensure_path() -> None:
    if str(_GUI_ROOT) not in sys.path:
        sys.path.insert(0, str(_GUI_ROOT))


def _sql_str(s: str) -> str:
    return (s or "").replace("'", "''")


def main() -> int:
    _ensure_path()
    from shared.service_mapping.rules import load_rule_pack, match_product_name

    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", required=True, help="discovery_crm_products CSV export")
    ap.add_argument("--out", required=True, help="Output .sql path")
    args = ap.parse_args()

    csv_path = Path(args.csv)
    out_path = Path(args.out)
    categories, rules = load_rule_pack()

    lines: list[str] = []
    lines.append("-- Generated by shared/service_mapping/generate_seed_sql.py")
    lines.append("-- CRM GUI service mapping: pages registry + per-product seed + view + legacy drop")
    lines.append("BEGIN;")
    lines.append("")
    lines.append("DROP VIEW IF EXISTS v_gui_crm_product_mapping CASCADE;")
    lines.append("DROP TABLE IF EXISTS gui_crm_service_mapping_seed CASCADE;")
    lines.append("DROP TABLE IF EXISTS gui_crm_service_mapping_override CASCADE;")
    lines.append("DROP TABLE IF EXISTS gui_crm_service_pages CASCADE;")
    lines.append("")
    lines.append("CREATE TABLE gui_crm_service_pages (")
    lines.append("    page_key          TEXT PRIMARY KEY,")
    lines.append("    category_label    TEXT NOT NULL,")
    lines.append("    gui_tab_binding   TEXT NOT NULL,")
    lines.append("    resource_unit     TEXT NOT NULL DEFAULT 'Adet',")
    lines.append("    icon              TEXT,")
    lines.append("    route_hint        TEXT,")
    lines.append("    tab_hint          TEXT,")
    lines.append("    sub_tab_hint      TEXT")
    lines.append(");")
    lines.append("")

    for pk, meta in sorted(categories.items(), key=lambda x: x[0]):
        lab = _sql_str(str(meta.get("label") or pk))
        gtb = _sql_str(str(meta.get("gui_tab_binding") or "other"))
        ru = _sql_str(str(meta.get("resource_unit") or "Adet"))
        lines.append(
            "INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) "
            f"VALUES ('{_sql_str(pk)}', '{lab}', '{gtb}', '{ru}');"
        )

    lines.append("")
    lines.append("CREATE TABLE gui_crm_service_mapping_seed (")
    lines.append("    productid   TEXT PRIMARY KEY,")
    lines.append("    page_key    TEXT NOT NULL REFERENCES gui_crm_service_pages(page_key)")
    lines.append(");")
    lines.append("")

    valid_pages = set(categories.keys())
    with open(csv_path, encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            pid = (row.get("productid") or "").strip().strip('"')
            name = (row.get("name") or "").strip()
            if not pid:
                continue
            page_key, _meta = match_product_name(name, categories=categories, rules=rules)
            if page_key not in valid_pages:
                page_key = "other"
            lines.append(
                "INSERT INTO gui_crm_service_mapping_seed (productid, page_key) "
                f"VALUES ('{_sql_str(pid)}', '{_sql_str(page_key)}');"
            )

    lines.append("")
    lines.append("CREATE TABLE gui_crm_service_mapping_override (")
    lines.append("    productid    TEXT PRIMARY KEY,")
    lines.append("    page_key     TEXT NOT NULL REFERENCES gui_crm_service_pages(page_key),")
    lines.append("    notes        TEXT,")
    lines.append("    updated_by   TEXT,")
    lines.append("    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()")
    lines.append(");")
    lines.append("")
    lines.append(
        "DO $migrate_manual$\n"
        "BEGIN\n"
        "  IF to_regclass('public.discovery_crm_product_category_alias') IS NOT NULL THEN\n"
        "    INSERT INTO gui_crm_service_mapping_override (productid, page_key, notes, updated_by, updated_at)\n"
        "    SELECT pca.productid,\n"
        "           CASE WHEN pca.category_code IN (SELECT page_key FROM gui_crm_service_pages)\n"
        "                THEN pca.category_code ELSE 'other' END,\n"
        "           COALESCE(pca.notes, 'migrated from discovery_crm_product_category_alias'),\n"
        "           'migration',\n"
        "           now()\n"
        "    FROM   discovery_crm_product_category_alias pca\n"
        "    WHERE  pca.source = 'manual';\n"
        "  END IF;\n"
        "END $migrate_manual$;"
    )
    lines.append("")
    lines.append("CREATE OR REPLACE VIEW v_gui_crm_product_mapping AS")
    lines.append("SELECT")
    lines.append("    pr.productid,")
    lines.append("    pr.name AS product_name,")
    lines.append("    pr.productnumber AS product_number,")
    lines.append("    COALESCE(o.page_key, s.page_key, 'other') AS category_code,")
    lines.append("    pg.category_label,")
    lines.append("    pg.gui_tab_binding,")
    lines.append("    COALESCE(NULLIF(TRIM(pg.resource_unit), ''), 'Adet') AS resource_unit,")
    lines.append(
        "    CASE WHEN o.productid IS NOT NULL THEN 'override' "
        "WHEN s.productid IS NOT NULL THEN 'yaml' ELSE 'default' END AS mapping_source"
    )
    lines.append("FROM   discovery_crm_products pr")
    lines.append("LEFT JOIN gui_crm_service_mapping_seed s ON s.productid = pr.productid")
    lines.append("LEFT JOIN gui_crm_service_mapping_override o ON o.productid = pr.productid")
    lines.append("JOIN   gui_crm_service_pages pg ON pg.page_key = COALESCE(o.page_key, s.page_key, 'other');")
    lines.append("")
    lines.append("DROP TABLE IF EXISTS discovery_crm_product_category_alias CASCADE;")
    lines.append("")
    lines.append("COMMIT;")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
